### PR TITLE
[WIP] move from hyper to reqwest

### PR DESCRIPTION
**Pull request by AlexKornitzer**
As per issue #110, I have decided to migrate rs-es from hyper to reqwest. Initially I started porting to the latest hyper version, but quickly found that we will just end up copying `oneshot` completion code from reqwest, so I just decided to take the level of abstraction one level higher. This migration was surprisingly easy due to the structure of rs-es. The benefits of reqwest apart from maintainability are that ability to build custom clients and pass these to rs-es, similar to that of the elastic rust library.

I have left this as WIP as I have not updated the documentation, or thoroughly tested.

### CODE REVIEW

**Comment by benashford** [comment]
Hello,

Yes, this is a good idea actually. It would still be a good idea for this library to go fully asynchronous in the fullness of time, as that seems to be where the wider Rust universe is going. But we can do that with Reqwest rather than lower-level Hyper code.

I'll have a fuller look into this over the next few days when I have some spare time.

Thanks!

**Comment by AlexKornitzer** [comment]
Awesome, it should be easy to add an AsyncBuilder too, but for my cases atm I only need Sync so I didn't add that. I might have to move to elastic 6 soon, so I may start updating the library handle that soon as well.

NOTE: The broken tests above are because I updated them to run on my ES5, so I will need to revert that as the library is not totally ES5 compatible.

**Comment by benashford** [comment]
Yes, we should leave making it async until a future change. Introducing Reqwest is a big enough change on its own and will solve a number of issues (e.g. SSL library compatibility issues).

**Comment by benashford** [comment]
I'm going to close PR as the goal should have been achieved by #126. While this wasn't a direct merge of this PR, I used this as a reference and it was very helpful 👍

**Pull request closed without merging**
