### PR TITLE
Implement settings

### PR DESCRIPTION
**Pull request by RoxasShadow**
This PR implements the `Settings` struct allowing users to configure their indexes, first of all in order to define their custom analyzers.

Unfortunately this is a broken change as I preferred following the pattern used in other modules of this projects in order to make the usage of `MappingOperation` more flexible.

### CODE REVIEW

**Comment by RoxasShadow** [comment]
The nightly test failed because of an (HTTP, I guess) error during the download of ElasticSearch.

I'm pretty sure that if travis ci makes a rebuild this PR should become all green.

**Comment by benashford** [comment]
Indeed, kicking-off Travis for a second time fixed it.

Since this is a breaking change, I'll put this as the first release of the 0.4 series, and I'll put the other breaking changes I was planning for 0.4 as a later 0.5 series when the time comes to it.

**Comment by benashford** [comment]
Published as 0.4.0

**Comment by benashford** [comment]
Hmm, GitHub thinks it's closed without merging.  But that's because I cherry-picked the commit into a different branch instead.  The change is definitely in master.

**Comment by RoxasShadow** [comment]
Yep, thank you.

**Pull request closed without merging**
