### PR TITLE
Implement Highlight

### PR DESCRIPTION
**Pull request by RoxasShadow**
#39

It should be quite usable at this point, except for `highlight_query` that needs to be implemented.

### CODE REVIEW

**Comment by benashford** [comment]
Cool!  Thanks for this.

The build failure seems to be something unrelated, even though the dependencies haven't changed since the last successful Travis build it has started failing on stable and beta channels.  Let me have a look into that build first, then I'll come back to this PR.

**Comment by benashford** [comment]
The build should now be fixed, it looks like a breaking change in how projects call the Serde project slipped through in a new patch version.

Could you merge master into your branch?  That should fix this build, and allow the pull request to be merged.

**Comment by RoxasShadow** [comment]
Done!

**Comment by benashford** [comment]
Cool, thank you!  I'll include this in a new release for `crates.io` later today.

**Comment by RoxasShadow** [comment]
Thank you 👍

**Comment by benashford** [comment]
Published as `0.4.3`

**Pull request merged**
