### PR TITLE
Make DecayOptions useful

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Currently, we can't set the `scale` field. This PR fixes it.

### CODE REVIEW

**Comment by benashford** [comment]
Cool, thanks for this.

I want to check ways of handling this with consistency elsewhere in the library, as a precautionary measure as I think there's some historic divergence anyway and this is a good opportunity to try and keep things consistent.

I'll come back to this later (I've put a label on to remind me) but I'm going to prioritise some of the other waiting PR/issues first. I intend to come back to this in the not too distant future.

**Comment by GuillaumeGomez** [comment]
Thanks! If needed, I can add same working way in other types if you want?

**Comment by GuillaumeGomez** [comment]
I didn't expect my second commit to fail the tests... It cannot connect to a server apparently...

**Comment by benashford** [comment]
I think that's just a coincidence. The `master` build is also failing for the same reason, something must have changed with how Travis run the builds.

**Comment by GuillaumeGomez** [comment]
Any news in here? I'm still using my branch for the moment but I'd like to be able to use the upstream again. :)

**Comment by GuillaumeGomez** [comment]
It's been a while now and I still need to use my own branch, preventing us to make a new release. Do you need help or something in order to make this branch merged?

**Comment by benashford** [comment]
Hello,

This should be good-to-go now. It was blocked for a while due to the (unrelated) build problems, but it all looks good now.

**Comment by GuillaumeGomez** [comment]
Awesome, thanks!

**Comment by benashford** [comment]
This is released in `0.11.5`

**Pull request merged**
