### PR TITLE
Hyper v1.0

### PR DESCRIPTION
**Pull request by RoxasShadow**
This PR upgrades hyper to the latest `hyper` version, which introduces asynchronous I/O thanks to `tokio`. Since they removed internal support to TLS/SSL, we'll get it from `hyper-openssl`.

Maybe we can give precedence to #97 as this PR is based on it.

### CODE REVIEW

**Comment by benashford** [comment]
Async I/O 🤔, that could be quite handy in future.

Before I merge, could you merge the latest `master` into this branch (or rebase).  The diff seems to be confused as is, it's comparing the new branch with an old `master` before #97 was merged in.  Updating this branch from `master` ought to clarify the history.

**Comment by KodrAus** [comment]
I think `hyper 0.10.x` is still based on synchronous IO from the standard library. So there isn't even `rotor` anymore. But it's the "long-term support" version for a synchronous API so is worth updating to.

You can target the `master` branch of `hyper` to see what it's async API looks like. It'll mean pulling in dependencies on `futures` and `tokio-core`.

**Comment by RoxasShadow** [comment]
I thought that hyper 0.10.* was relatively on the same line of updates of the master branch, but you made me realize that [it is not](https://crates.io/crates/hyper) as tokio is not a dependency of it. 

Thanks for the highlight.

**Comment by benashford** [comment]
Cool, thanks 👍 

I'll package the last two PRs as a `v0.8.0` release later today.

**Comment by benashford** [comment]
Released as `0.8.0`

**Pull request merged**
