### PR TITLE
Implement Boolean type for JsonVal

### PR DESCRIPTION
**Pull request by RoxasShadow**
Add support for the [ES Boolean datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/boolean.html) to Rust `bool`eans.

### CODE REVIEW

**Comment by benashford** [comment]
Cool.  Thank you.

**Comment by RoxasShadow** [comment]
Thank you for merging this. Would be great if you publish a new version of rs-es on crate.io

**Comment by benashford** [comment]
The HEAD of `master` is currently in a slightly inconsistent state, it's not quite ready for a new release just yet.  Hopefully in a week or two.

In the meantime would importing the project as a git dependency help? (e.g., the examples here: http://doc.crates.io/guide.html#cargotoml-vs-cargolock)

**Comment by RoxasShadow** [comment]
I see.

I'm already doing that, but unfortunately my tests always die on CircleCI due to a bug in Cargo.

>$<2>$<2>    Updating$<2> registry `https://github.com/rust-lang/crates.io-index`
$<2>Unable to update registry https://github.com/rust-lang/crates.io-index
$<2>$<2>
Caused by:
$<2>$<2>  failed to fetch `https://github.com/rust-lang/crates.io-index`
$<2>$<2>
Caused by:
$<2>$<2>  failed to authenticate when downloading repository
$<2>$<2>
Caused by:
$<2>$<2>  [23/-1] error authenticating: no auth sock variable

$<2>cargo build -v returned exit code 101

**Comment by benashford** [comment]
I've backported your change to the 0.2.x series, and released on crates.io as 0.2.1: https://crates.io/crates/rs-es

Hopefully this should help.

But the 0.2.x series is the one targeting ES 1.6, but it should be (mostly) forward compatible, but any ES 2.0 or later features won't be available until the 0.3 releases are ready.

**Pull request merged**
